# Generated by Django 3.1.5 on 2021-01-08 15:24

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.DateTimeField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='User nickname')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Date of creating the user')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main_app.group', verbose_name=main_app.models.Group)),
            ],
        ),
    ]
